name: Create PR from Release to master

env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground
  TEMP_BRANCH_LISTEN_CHANGE: create-pull-request/patch

on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: $BASE_BRANCH

      - name: Reset promotion branch
        run: |
          git fetch origin $HEAD_BRANCH:$HEAD_BRANCH
          git reset --hard $HEAD_BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: $TEMP_BRANCH_LISTEN_CHANGE
