name: Create PR from 'stag-playground' to 'master' after push to Release

on:
  push:
    branches:
      - stag-playground
env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Log env
        run: echo $BASE_BRANCH # Uses the global environment variable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check differences
        id: check_diff
        run: |
          git fetch origin $BASE_BRANCH
          git diff --quiet origin/$BASE_BRANCH origin/$HEAD_BRANCH || echo "differences found"
          echo ${{ steps.check_diff.outputs }}

      - name: Crate Pull Request
        id: cpr
        if: steps.check_diff.outputs.differences_found == 'differences found'
        uses: peter-evans/create-pull-request@v7.0.1
        with:
          title: "Merge branch '$BASE_BRANCH' into '$HEAD_BRANCH'"
          body: 'This PR was created from Github Action "Create PR from Release to Main after push to Release"'
          base: $BASE_BRANCH
          head: $HEAD_BRANCH
          labels: auto:github_action

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
