name: Create PR - Update 'master' with 'stag-playground' new push

# Doc_1: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
# Doc_2: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-behaviour

env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground
  TEMP_BRANCH_LISTEN_CHANGE: create-pull-request/patch

on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ env.HEAD_BRANCH }}:${{ env.HEAD_BRANCH }}
          git reset --hard ${{ env.HEAD_BRANCH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.TEMP_BRANCH_LISTEN_CHANGE }}
