name: Create PR from Release to master

env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground
  TEMP_BRANCH_LISTEN_CHANGE: create-pull-request/patch

on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ env.HEAD_BRANCH }}:${{ env.HEAD_BRANCH }}
          git reset --hard ${{ env.HEAD_BRANCH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.TEMP_BRANCH_LISTEN_CHANGE }}
