name: Create PR from Release to Main

on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Merge changes from release into main'
          body: 'This PR merges the latest changes from the release branch into the main branch.'
          base: main
          branch: stag-playground
