name: Create PR from Release to master
# 1
on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout github
        runs: 'git checkout master'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Merge changes from release into master'
          body: 'This PR merges the latest changes from the release branch into the master branch.'
          base: master
          branch: stag-playground
          draft: false
