name: Create PR from Release to master
# 123
on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: create-pull-request/patch

      - name: Reset promotion branch
        run: |
          git fetch origin stag-playground:stag-playground
          git reset --hard stag-playground

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: production-promotion
