name: Create PR from 'stag-playground' to 'master' after push to Release
# on 'push' event require set up token key https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
# change - 1
on:
  push:
    branches:
      - stag-playground
env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Log env
        run: |
          echo $BASE_BRANCH # Uses the global environment variable
          echo ${{ secrets }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Crate Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.pat }}
          commit-message: 'merge branch'
          base: master
          branch: stag-playground
          title: '[Example] Update report'

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
