name: Create PR from Release to master
# 123
on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git checkout master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
