name: Create PR - Update 'master' with 'stag-playground' new push

# Doc_1: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
# Doc_2: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-behaviour
# .

permissions:
  contents: write
  pull-requests: write

env:
  BASE_BRANCH: master
  HEAD_BRANCH: stag-playground
  TEMP_BRANCH_LISTEN_CHANGE: create-pull-request/patch

on:
  push:
    branches:
      - stag-playground

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: create pull request
        run: gh pr create --base ${{ env.BASE_BRANCH }} --head ${{ env.HEAD_BRANCH }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action' --label auto:github-actions --reviewer khanaru220,vanhuynh
